- name: Setup master node with Calico CNI (1/8)...
  tags:
   - k8s
  ansible.builtin.shell:
    cmd: |
      KUBERNETES_VERSION=$(kubeadm version | grep -oP '(^|[ ,])GitVersion:\K[^,]*' | tr -d \")
      kubeadm init --token=${TOKEN} --kubernetes-version=${KUBERNETES_VERSION} --pod-network-cidr=10.244.0.0/16
    creates: /etc/kubernetes/kubelet.conf
  register: k8sinit_output
  when: cni == "calico"

- name: Setup master node with Cilium CNI (1/8)...
  tags:
   - k8s
  ansible.builtin.shell:
    cmd: |
      KUBERNETES_VERSION=$(kubeadm version | grep -oP '(^|[ ,])GitVersion:\K[^,]*' | tr -d \")
      kubeadm init --token=${TOKEN} --kubernetes-version=${KUBERNETES_VERSION} --pod-network-cidr=10.244.0.0/16 --skip-phases=addon/kube-proxy
    creates: /etc/kubernetes/kubelet.conf
  register: k8sinit_output
  when: cni == "cilium"

- name: Setup master node (2/8)...
  tags:
   - k8s
  ansible.builtin.copy:
    content: '{{ k8sinit_output.stdout }}'
    dest: cluster_join_file
  when: '"token" in k8sinit_output.stdout'

- name: Setup master node (3/8)...
  tags:
   - k8s
  ansible.builtin.fetch:
    flat: yes
    src: cluster_join_file
    dest: static/token_file
  when: '"token" in k8sinit_output.stdout'

- name: Setup master node (4/8)...
  tags:
   - k8s
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: Setup master node (5/8)...
  tags:
   - k8s
  ansible.builtin.shell:
    cmd: |
      cp /etc/kubernetes/admin.conf $HOME/.kube/config
      chown $(id -u):$(id -g) $HOME/.kube/config

- name: Setup master node (6/8)...
  tags:
   - k8s
  ansible.builtin.fetch:
    flat: yes
    src: $HOME/.kube/config
    dest: static/kubeconfig

- name: Setup master node (7/8)...
  ansible.builtin.pause:
    minutes: 1

- name: Setup master node (8/8)...
  tags:
   - k8s
  shell:
    cmd: |
      kubectl taint node master node-role.kubernetes.io/master:NoSchedule-
      kubectl label nodes master node-type=master

- name: Installing required CNI (1/1)...
  tags:
   - k8s
  shell:
    cmd: |
      kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
  when: cni == "calico"


### NFS Server

- name: Setup NFS Server (1/6)...
  tags:
  - nfs
  file:
    path: /mnt/nfs
    state: directory

- name: Setup NFS Server (2/6)...
  tags:
  - nfs
  package:
    name:
      - nfs-kernel-server
    update_cache: yes

- name: Setup NFS Server (3/6)...
  tags:
  - nfs
  ansible.builtin.service:
    name: nfs-server
    enabled: yes

- name: Setup NFS Server (4/6)...
  tags:
  - nfs
  ansible.posix.mount:
    path: /mnt/nfs
    src: "{{ nfs_device_path }}"
    fstype: ext4
    opts: rw,defaults,noatime,nodiratime
    state: mounted

- name: Setup NFS Server (5/6)...
  tags:
  - nfs
  copy:
    src: files/exports
    dest: /etc/exports

- name: Setup NFS Server (6/6)...
  tags:
  - nfs
  ansible.builtin.service:
    name: nfs-server
    state: restarted