- hosts: all
  become: yes
  pre_tasks:
    - name: Restarting hosts pre upgrade...
      tags: pre
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 60

    - name: Update system packages...
      tags: pre
      apt:
        upgrade: yes # No dist upgrade
        update_cache: yes

    - name: Restarting hosts post upgrade...
      tags: pre
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 60

- hosts: all
  become: yes
  roles:
  - role: k8s-containerd

- hosts: master
  become: yes
  roles:
  - role: master

- hosts: workers
  become: true
  roles:
  - role: worker
