- hosts: all
  become: yes
  tasks:
    - name: Resetting kubernetes...
      shell:
        cmd: |
          kubeadm reset -f
          rm -rf ~/.kube
          rm -rf /etc/kubernetes
          rm -rf /var/lib/etcd/

    - name: Restarting hosts...
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 60
        test_command: whoami

    - name: Configuring host (1/4)...
      modprobe:
        name: overlay
        state: present

    - name: Configuring host (2/4)...
      modprobe:
        name: br_netfilter
        state: present

    - name: Configuring host (3/4)...
      modprobe:
        name: dummy
        state: present

    - name: Restarting hosts (4/4)...
      ansible.builtin.shell:
        cmd: |
          ip link set dev eth0 promisc on
          ip link set dev wlan0 promisc on
          swapoff -a
          sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab