- hosts: all
  become: yes
  tasks:
    - name: Reset kubernetes
      shell:
        cmd: |
          kubeadm reset -f

    - name: Restarting hosts (1/3)...
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 60
        test_command: whoami

    - name: Restarting hosts (2/3)...
      modprobe:
        name: br_netfilter
        state: present

    - name: Restarting hosts (3/3)...
      ansible.builtin.shell:
        cmd: |
          ip link set dev eth0 promisc on
          swapoff -a
          sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab